[workspace]
resolver = "2"
members = ["hazel-core"]


[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[profile.release]
opt-level = 3
debug = true

[profile.mutants]
inherits = "test"
debug = false
debug-assertions = false
opt-level = 3


[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
