[package]
name = "hazel"
version = "0.1.0"
authors = ["Joe Fredette <jfredett@gmail.com>"]
description = "Chess Engine"
edition = "2021"

[lib]
name="hazel"
bench = false
path="src/lib.rs"

[[bin]]
name="hazel"
path="src/main.rs"

[dependencies]
clap = { version = "2.33", features = ["yaml"]}
lazy_static = "1.4.0"
either = "1.12"
rand = "0.8.5"
tracing = "*"
serde = { version = "1.0.203", features = ["derive"] }
bincode = "1.3.3"
pgn-reader = "0.26.0"
anyhow = "1.0.42"
thiserror = "1.0.61"


[dev-dependencies]
criterion = "*"
criterion-macro = "*"
quickcheck = "*"
quickcheck_macros = "*"
paste = "*"
tracing-test = "*"

[[bench]]
name = "benchmarks"
harness = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[profile.release]
opt-level = 3
debug = true
