[package]
name = "hazel"
version = "0.1.0"
authors = ["Joe Fredette <jfredett@gmail.com>"]
description = "Chess Engine"
edition = "2018"

[lib]
name="hazel"
bench = false
path="src/lib.rs"

[[bin]]
name="hazel"
path="src/main.rs"

[dependencies]
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
clap = { version = "~2.33", features = ["yaml"]}
bitflags = "~1.2"
log = "~0.4"
fern = "~0.5"
lazy_static = "~1.4"

[dev-dependencies]
rand = "~0.7"
criterion = "~0.3"
criterion-macro = "~0.3"
quickcheck = "~1.0"
quickcheck_macros = "~1.0"

[[bench]]
name = "benchmarks"
harness = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

