[package]
name = "hazel"
version = "0.1.0"
authors = ["Joe Fredette <jfredett@gmail.com>"]
description = "Chess Engine"
edition = "2021"

[lib]
name="hazel"
bench = false
path="src/lib.rs"

[[bin]]
name="hazel"
path="src/main.rs"

[dependencies]
clap = { version = "2.33", features = ["yaml"]}
yaml-rust = "0.4.1"
lazy_static = "1.4.0"
either = "1.12"
rand = "0.8.5"
tracing = "*"
serde = { version = "1.0.203", features = ["derive"] }
bincode = "1.3.3"
pgn-reader = "0.26.0"
thiserror = "1.0.61"
ratatui = "0.27.0"
serde_json = "1.0.117"
nom = "7.1.3"



[dev-dependencies]
criterion = "0.4.0"
criterion-macro = "0.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
paste = "1.0.15"
tracing-test = "0.2.5"

[[bench]]
name = "benchmarks"
harness = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[profile.release]
opt-level = 3
debug = true
