[package]
name = "hazel"
version = "0.1.0"
authors = ["Joe Fredette <jfredett@gmail.com>"]
description = "Chess Engine"
edition = "2021"

[lib]
name="hazel"
bench = false
path="src/lib.rs"

[[bin]]
name="hazel"
path="src/main.rs"


# I might featureflag some stuff, e.g., serde and that, to reduce compile times?

[dependencies]

async-trait = "0.1.87"
clap = { version = "2.33", features = ["yaml"]}
console-subscriber = "0.4.1"
const-str = "0.6.2"
crossbeam = "0.8.4"
dynamic-array = "0.2.3"
itertools = "0.14.0"
lazy_static = "1.4.0"
nom = "7.1.3"
rand = "0.8.5"
ratatui = "0.29.0"
rayon = "1.10.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
similar-asserts = "1.7.0"
tokio = { version = "1.44.0", features = ["full"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.14", features = ["io"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
yaml-rust = "0.4.1"

[dev-dependencies]
criterion = "0.5.1"
criterion-macro = "0.4.0"
insta = "1.42.2"
mutants = "0.0.3"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
similar-asserts = "1.6.1"
tracing-test = "0.2.5"

# Removing benchmarking temporarily
#[[bench]]
#name = "benchmarks"
#harness = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[profile.release]
opt-level = 3
debug = true

[profile.mutants]
inherits = "test"
debug = false
debug-assertions = false
opt-level = 3


[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
