[package]
name = "hazel"
version = "0.1.0"
authors = ["Joe Fredette <jfredett@gmail.com>"]
description = "Chess Engine"
edition = "2021"

[lib]
name="hazel"
bench = false
path="src/lib.rs"

[[bin]]
name="hazel"
path="src/main.rs"

[dependencies]
clap = { version = "2.33", features = ["yaml"]}
yaml-rust = "0.4.1"
lazy_static = "1.4.0"
either = "1.12"
rand = "0.8.5"
tracing = "0.1"
serde = { version = "1.0.203", features = ["derive"] }
bincode = "1.3.3"
pgn-reader = "0.26.0"
thiserror = "1.0.61"
ratatui = "0.27.0"
serde_json = "1.0.117"
nom = "7.1.3"
rayon = "1.10.0"
crossbeam = "0.8.4"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.16.0", features = ["full"] }
tokio-stream = "0.1.16"
tokio-util = { version = "0.7.12", features = ["io"] }


[dev-dependencies]
criterion = "0.4.0"
criterion-macro = "0.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
paste = "1.0.15"
tracing-test = "0.2.5"
cargo-llvm-cov = "0.6.11"
cargo-nextest = "0.9.72"
#cargo-mutants = "24.7.1"

[[bench]]
name = "benchmarks"
harness = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[profile.release]
opt-level = 3
debug = true
