[package]
name = "hazel"
version = "0.1.0"
authors = ["Joe Fredette <jfredett@gmail.com>"]
description = "Chess Engine"
edition = "2021"

[lib]
name="hazel"
bench = false
path="src/lib.rs"

[[bin]]
name="hazel"
path="src/main.rs"


# I might featureflag some stuff, e.g., serde and that, to reduce compile times?

[dependencies]
clap = { version = "2.33", features = ["yaml"]}
yaml-rust = "0.4.1"
lazy_static = "1.4.0"
rand = "0.8.5"
tracing = "0.1"
serde = { version = "1.0.215", features = ["derive"] }
pgn-reader = "0.26.0"
ratatui = "0.29.0"
serde_json = "1.0.117"
rayon = "1.10.0"
crossbeam = "0.8.4"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.16.0", features = ["full"] }
tokio-stream = "0.1.16"
tokio-util = { version = "0.7.12", features = ["io"] }
const-str = "0.5.7"
mutants = "0.0.3"

[dev-dependencies]
criterion = "0.5.1"
criterion-macro = "0.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tracing-test = "0.2.5"

# Removing benchmarking temporarily
#[[bench]]
#name = "benchmarks"
#harness = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[profile.release]
opt-level = 3
debug = true

[profile.mutants]
inherits = "test"
debug = false
debug-assertions = false
opt-level = 3

