name: Tests & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build

    - name: Install just
      uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6

    - name: Install Nextest
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-nextest

    - name: Install Stockfish
      run: sudo apt install -y stockfish

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Run Tests
      run: just ci

    - name: Generate code coverage
      run: just coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: .lcov
        fail_ci_if_error: false
