name: Tests & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

    - name: Setup just
      uses: extractions/setup-just@v2

    - name: Install Nextest
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-nextest
    - name: Install Stockfish
      run: sudo apt install -y stockfish
    - name: Run Tests
      run: just test
    - name: Run Doctests
      run: cargo test --doc

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Generate code coverage
      run: cargo llvm-cov --all-features --workspace
