name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:      
    runs-on: ubuntu-latest

    steps:
    - name: Setup just
      uses: extractions/setup-just@v2
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: just test
    - name: Run Coverage
      run: just coverage
